mongo:
  hostname: 127.0.0.1
  port: 27018
  username: trader
  password: trader123456
  database: trader

redis:
  hostname: 127.0.0.1
  port: 6380
  sets: 
    success: fetch_success
    fail: fetch_fail
  maps:
    handle: handle_fail
  prefix: trader-
  hsetname: TraderFetch