version: '3'

services:
  trader: 
    image: go-trader/go-trader:latest
    container_name: go-trader
    ports: 
      - "3001:3001"
    command: ["/app/go-trader/go-trader", "test"]
    environment:
      - APP_DOMAIN=localhost
      - ROOT_URL=http://localhost:3001
      - DB_MONGO_HOST=mongo:27018
      - DB_MONGO_PASSWD=trader123456
      - DB_MONGO_USERNAME=trader
      - DB_MONGO_DB=trader
      - REDIS_URL=redis://redis:6380/0
      - CRON_ENABLED=false

  mongo:
    image: mongo:4.2.13-bionic
    container_name: trader_mongo
    ports:
      - "27018:27017"
    volumes: 
      # - ./.database/mongodb/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
      - ./.database/mongodb/data:/data/db
    command: ["mongod", "--auth"]

  redis:
    image: redis
    container_name: trader_redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes: 
      - ./.database/redis/data:/data